version: '3.9'

services:
  backend-server:
    build:
      context: .
    container_name: backend-server
    environment:
      - DB_HOST=database
    networks:
      - seollal-bootcamp-2025-backend
    ports:
      - "8080:8080"
    restart: always

networks:
  seollal-bootcamp-2025-backend:
    driver: bridge
