on:
- push

name: Build and deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: "Checkout Github Action"
      uses: actions/checkout@v4

    - name: "Docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: "Image build and push"
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/ecommerce:${{ github.sha }}

    # - name: Azure login
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     auth-type: IDENTITY

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: "example-web-app-codeseoul-beege"
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/ecommerce:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
